/* This is a translation of q.bf, generated by bftoc.py (by Paul Kaefer)
 * It was generated on Saturday, October 24, 2020 at 08:28AM
 */

#include <stdio.h>

void main(void)
{
    int size = 1000;
    int tape[size];
    int i = 0;

    /* Clearing the tape (array) */
    for (i=0; i<size; i++)
        tape[i] = 0;

    int ptr = 0;

    ptr += 1;
    tape[ptr] = getchar();
    ptr -= 1;
    ptr += 2;
    tape[ptr] = getchar();
    ptr += 1;
    tape[ptr] = getchar();
    ptr -= 1;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 1;
        ptr += 1;
        tape[ptr] -= 1;
        ptr += 1;
        tape[ptr] += 1;
        ptr -= 1;
        ptr += 1;
        ptr -= 2;
    }
    tape[ptr] += 1;
    tape[ptr] -= 1;
    ptr += 2;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 1;
        ptr -= 2;
        tape[ptr] += 1;
        ptr += 2;
    }
    ptr -= 1;
    tape[ptr] += 1;
    tape[ptr] -= 1;
    ptr += 1;
    ptr -= 1;
    ptr += 1;
    ptr -= 3;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 1;
        tape[ptr] += 1;
        tape[ptr] -= 1;
        ptr += 1;
        tape[ptr] -= 1;
        ptr -= 1;
        tape[ptr] += 1;
        tape[ptr] -= 1;
        ptr -= 1;
        tape[ptr] += 1;
        ptr += 1;
    }
    ptr -= 1;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 1;
        ptr += 1;
        tape[ptr] += 1;
        ptr -= 1;
    }
    ptr += 1;
    ptr -= 1;
    ptr += 6;
    ptr -= 1;
    ptr += 1;
    tape[ptr] += 2;
    tape[ptr] -= 1;
    ptr += 2;
    tape[ptr] += 1;
    tape[ptr] -= 1;
    ptr += 5;
    tape[ptr] += 1;
    while (tape[ptr] != 0)
    {
        ptr += 2;
        ptr -= 1;
        ptr += 3;
        while (tape[ptr] != 0)
        {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0)
        {
            tape[ptr] -= 1;
            ptr -= 1;
            ptr += 1;
            tape[ptr] -= 1;
            tape[ptr] += 1;
        }
        ptr -= 2;
        ptr += 1;
        while (tape[ptr] != 0)
        {
            tape[ptr] -= 1;
            tape[ptr] += 1;
            tape[ptr] -= 1;
        }
        tape[ptr] -= 1;
        tape[ptr] += 2;
        tape[ptr] -= 1;
        tape[ptr] += 1;
        tape[ptr] -= 1;
        ptr -= 1;
        while (tape[ptr] != 0)
        {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        ptr += 1;
        ptr -= 2;
        ptr += 1;
        while (tape[ptr] != 0)
        {
            tape[ptr] += 1;
            tape[ptr] -= 3;
            tape[ptr] += 1;
        }
        ptr -= 1;
        ptr += 1;
        ptr -= 4;
        tape[ptr] += 1;
        tape[ptr] -= 1;
        ptr -= 4;
        ptr += 1;
        tape[ptr] -= 1;
        tape[ptr] += 1;
        ptr -= 1;
        ptr += 1;
        ptr -= 3;
        ptr += 1;
        ptr -= 1;
        tape[ptr] += 1;
        tape[ptr] -= 1;
        ptr -= 2;
        while (tape[ptr] != 0)
        {
            tape[ptr] -= 1;
            ptr += 7;
            tape[ptr] += 1;
            ptr += 5;
            tape[ptr] -= 1;
            tape[ptr] += 1;
            ptr += 1;
            tape[ptr] += 1;
            ptr -= 3;
            ptr += 1;
            ptr -= 3;
            ptr += 1;
            ptr -= 9;
        }
        ptr += 1;
        while (tape[ptr] != 0)
        {
            tape[ptr] -= 1;
            ptr += 5;
            ptr -= 1;
            ptr += 1;
            ptr -= 1;
            ptr += 2;
            ptr -= 1;
            ptr += 2;
            tape[ptr] += 1;
            ptr += 6;
            tape[ptr] += 1;
            ptr -= 5;
            ptr += 1;
            ptr -= 5;
            tape[ptr] += 1;
            tape[ptr] -= 1;
            ptr -= 4;
        }
        ptr += 1;
        while (tape[ptr] != 0)
        {
            tape[ptr] -= 1;
            ptr += 7;
            ptr -= 1;
            ptr += 1;
            tape[ptr] += 1;
            ptr += 4;
            tape[ptr] -= 1;
            tape[ptr] += 1;
            ptr += 1;
            ptr -= 1;
            ptr += 2;
            tape[ptr] += 1;
            ptr -= 6;
            tape[ptr] += 1;
            tape[ptr] -= 1;
            ptr -= 4;
            ptr += 1;
            ptr -= 4;
            tape[ptr] -= 1;
            tape[ptr] += 1;
            ptr += 1;
            ptr -= 1;
        }
        ptr += 2;
        tape[ptr] -= 1;
        tape[ptr] += 2;
        tape[ptr] -= 1;
        tape[ptr] += 1;
        ptr += 1;
        tape[ptr] += 1;
        tape[ptr] -= 1;
        tape[ptr] += 1;
        while (tape[ptr] != 0)
        {
            ptr -= 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0)
        {
            tape[ptr] -= 1;
            ptr += 2;
            ptr -= 1;
            ptr += 1;
            tape[ptr] += 2;
            tape[ptr] -= 1;
            ptr -= 3;
        }
        ptr += 4;
        while (tape[ptr] != 0)
        {
            tape[ptr] -= 1;
            ptr -= 3;
            tape[ptr] += 1;
            tape[ptr] -= 2;
            tape[ptr] += 1;
            ptr -= 4;
            tape[ptr] += 1;
            ptr += 2;
            ptr -= 1;
            ptr += 6;
        }
        ptr += 1;
        while (tape[ptr] != 0)
        {
            tape[ptr] -= 1;
            ptr -= 2;
            tape[ptr] -= 1;
            tape[ptr] += 1;
            ptr -= 5;
            tape[ptr] += 1;
            ptr -= 1;
            ptr += 2;
            tape[ptr] += 1;
            tape[ptr] -= 1;
            ptr += 6;
        }
        ptr += 1;
        while (tape[ptr] != 0)
        {
            tape[ptr] -= 1;
            ptr -= 4;
            ptr += 1;
            ptr -= 3;
            ptr += 1;
            ptr -= 2;
            tape[ptr] += 1;
            ptr += 7;
        }
        ptr += 6;
        ptr -= 1;
        ptr += 2;
        tape[ptr] += 1;
        while (tape[ptr] != 0)
        {
            tape[ptr] -= 1;
            ptr -= 4;
            tape[ptr] += 1;
            tape[ptr] -= 2;
            tape[ptr] += 1;
            ptr -= 1;
            ptr += 1;
            ptr -= 1;
            tape[ptr] += 1;
            tape[ptr] -= 1;
            ptr -= 6;
            while (tape[ptr] != 0)
            {
                tape[ptr] -= 1;
                ptr += 2;
                tape[ptr] += 1;
                ptr += 2;
                tape[ptr] += 1;
                ptr -= 4;
            }
            tape[ptr] += 1;
            tape[ptr] -= 1;
            ptr += 1;
            while (tape[ptr] != 0)
            {
                tape[ptr] -= 1;
                ptr += 2;
                tape[ptr] += 1;
                ptr += 2;
                tape[ptr] += 1;
                tape[ptr] -= 1;
                tape[ptr] += 1;
                ptr -= 4;
            }
            ptr += 1;
            while (tape[ptr] != 0)
            {
                tape[ptr] -= 1;
                ptr -= 2;
                tape[ptr] += 1;
                ptr += 2;
            }
            ptr += 1;
            while (tape[ptr] != 0)
            {
                tape[ptr] -= 1;
                ptr -= 2;
                tape[ptr] += 1;
                ptr += 2;
            }
            tape[ptr] += 1;
            while (tape[ptr] != 0)
            {
                while (tape[ptr] != 0)
                {
                    ptr -= 1;
                    ptr += 1;
                    tape[ptr] -= 1;
                }
                tape[ptr] -= 1;
                tape[ptr] += 2;
                ptr += 1;
                while (tape[ptr] != 0)
                {
                    ptr -= 1;
                    tape[ptr] -= 1;
                }
                ptr -= 1;
                tape[ptr] += 1;
                tape[ptr] -= 1;
                while (tape[ptr] != 0)
                {
                    tape[ptr] += 1;
                    tape[ptr] -= 2;
                    ptr += 1;
                    ptr -= 1;
                    ptr += 2;
                    ptr -= 1;
                    ptr += 1;
                    tape[ptr] -= 1;
                    ptr -= 3;
                }
                ptr += 2;
                tape[ptr] -= 1;
                tape[ptr] += 1;
                tape[ptr] -= 1;
                ptr += 3;
                tape[ptr] += 1;
                ptr += 1;
                while (tape[ptr] != 0)
                {
                    ptr -= 1;
                    tape[ptr] -= 1;
                }
                ptr -= 1;
                tape[ptr] += 1;
                tape[ptr] -= 1;
                while (tape[ptr] != 0)
                {
                    tape[ptr] -= 1;
                    ptr += 1;
                    tape[ptr] += 1;
                    ptr += 1;
                    while (tape[ptr] != 0)
                    {
                        tape[ptr] -= 1;
                        ptr -= 1;
                        tape[ptr] -= 1;
                    }
                    ptr -= 1;
                    while (tape[ptr] != 0)
                    {
                        ptr += 2;
                        while (tape[ptr] != 0)
                        {
                            tape[ptr] -= 1;
                            ptr -= 2;
                            tape[ptr] -= 1;
                            tape[ptr] += 1;
                            tape[ptr] -= 1;
                            ptr += 1;
                        }
                        tape[ptr] -= 1;
                        ptr -= 2;
                        while (tape[ptr] != 0)
                        {
                            tape[ptr] -= 1;
                            ptr += 2;
                            ptr -= 1;
                            tape[ptr] -= 1;
                            ptr += 1;
                            tape[ptr] += 1;
                            tape[ptr] -= 1;
                            ptr += 1;
                            tape[ptr] -= 1;
                            tape[ptr] += 1;
                            tape[ptr] -= 1;
                            ptr -= 4;
                        }
                    }
                    ptr -= 1;
                }
                ptr += 2;
                tape[ptr] -= 1;
                ptr -= 5;
                tape[ptr] += 1;
                ptr += 1;
                while (tape[ptr] != 0)
                {
                    ptr += 1;
                    ptr -= 2;
                    tape[ptr] -= 1;
                }
                ptr -= 1;
                while (tape[ptr] != 0)
                {
                    ptr += 1;
                    tape[ptr] += 1;
                    tape[ptr] -= 1;
                    ptr += 1;
                    while (tape[ptr] != 0)
                    {
                        tape[ptr] -= 1;
                        tape[ptr] += 1;
                        ptr -= 2;
                        tape[ptr] -= 1;
                        ptr += 1;
                    }
                    ptr -= 2;
                    while (tape[ptr] != 0)
                    {
                        ptr -= 1;
                    }
                }
                ptr += 1;
                tape[ptr] -= 1;
                tape[ptr] += 1;
                tape[ptr] -= 1;
            }
            ptr += 5;
            ptr -= 1;
            ptr += 4;
            ptr -= 1;
            ptr += 1;
            tape[ptr] += 1;
        }
        tape[ptr] -= 1;
        ptr -= 3;
        ptr += 1;
        tape[ptr] += 1;
        tape[ptr] -= 1;
        ptr -= 3;
        ptr += 1;
        tape[ptr] += 1;
        ptr += 1;
        tape[ptr] -= 1;
        tape[ptr] += 2;
        while (tape[ptr] != 0)
        {
            ptr -= 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0)
        {
            tape[ptr] -= 1;
            tape[ptr] += 1;
            ptr += 2;
            tape[ptr] += 1;
            while (tape[ptr] != 0)
            {
                ptr -= 3;
                ptr += 1;
                tape[ptr] -= 1;
                ptr += 1;
                tape[ptr] -= 1;
                tape[ptr] += 1;
            }
            ptr -= 2;
            while (tape[ptr] != 0)
            {
                ptr += 3;
                tape[ptr] += 1;
                while (tape[ptr] != 0)
                {
                    ptr -= 1;
                    tape[ptr] -= 1;
                    tape[ptr] += 1;
                    ptr -= 2;
                    tape[ptr] -= 1;
                    ptr += 2;
                }
                ptr -= 3;
                while (tape[ptr] != 0)
                {
                    ptr -= 1;
                }
            }
        }
        ptr += 1;
        tape[ptr] -= 1;
    }
    ptr += 4;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 1;
    }
    ptr -= 7;
    tape[ptr] -= 1;
    tape[ptr] += 1;
    ptr -= 1;
    ptr += 1;
    ptr -= 7;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 1;
    }
    ptr += 2;
    tape[ptr] += 1;
    ptr += 1;
    tape[ptr] += 1;
    while (tape[ptr] != 0)
    {
        ptr -= 1;
        tape[ptr] -= 1;
    }
    ptr -= 1;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 1;
        ptr += 2;
        tape[ptr] += 1;
        ptr -= 1;
        ptr += 1;
        ptr -= 3;
    }
    ptr += 1;
    tape[ptr] += 1;
    ptr += 1;
    while (tape[ptr] != 0)
    {
        ptr -= 1;
        tape[ptr] -= 1;
    }
    ptr -= 1;
    while (tape[ptr] != 0)
    {
        ptr += 2;
        while (tape[ptr] != 0)
        {
            ptr -= 2;
            tape[ptr] -= 1;
            ptr += 1;
        }
        ptr -= 2;
        while (tape[ptr] != 0)
        {
            ptr -= 1;
        }
    }
    ptr += 1;
    tape[ptr] -= 1;
    while (tape[ptr] != 0)
    {
        tape[ptr] += 1;
        ptr += 7;
        ptr -= 1;
        tape[ptr] += 2;
        tape[ptr] -= 1;
        tape[ptr] += 9;
        ptr -= 6;
        tape[ptr] += 1;
        ptr += 1;
        tape[ptr] += 1;
        tape[ptr] -= 1;
        while (tape[ptr] != 0)
        {
            ptr -= 2;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0)
        {
            ptr += 2;
            while (tape[ptr] != 0)
            {
                ptr -= 2;
                tape[ptr] -= 1;
                ptr += 1;
            }
            ptr -= 2;
            while (tape[ptr] != 0)
            {
                ptr -= 1;
            }
        }
        ptr += 1;
        tape[ptr] -= 1;
        while (tape[ptr] != 0)
        {
            tape[ptr] += 2;
            ptr += 1;
            while (tape[ptr] != 0)
            {
                ptr -= 1;
                tape[ptr] -= 1;
            }
            ptr -= 1;
            while (tape[ptr] != 0)
            {
                tape[ptr] -= 1;
                ptr += 2;
                tape[ptr] -= 1;
                ptr -= 3;
            }
            ptr += 2;
            tape[ptr] -= 1;
            ptr += 2;
            tape[ptr] += 1;
            ptr += 2;
            tape[ptr] += 1;
            ptr += 1;
            tape[ptr] -= 1;
            while (tape[ptr] != 0)
            {
                ptr -= 1;
                tape[ptr] -= 1;
            }
            ptr -= 1;
            while (tape[ptr] != 0)
            {
                ptr -= 2;
                while (tape[ptr] != 0)
                {
                    tape[ptr] -= 1;
                    ptr += 3;
                    tape[ptr] += 1;
                    ptr -= 2;
                    ptr += 1;
                    ptr -= 2;
                }
                tape[ptr] += 1;
                tape[ptr] -= 1;
                ptr += 5;
                tape[ptr] += 1;
                ptr += 1;
                tape[ptr] += 1;
                while (tape[ptr] != 0)
                {
                    ptr -= 1;
                    ptr += 1;
                    ptr -= 1;
                    tape[ptr] -= 1;
                }
                ptr -= 1;
                ptr += 1;
                ptr -= 1;
                while (tape[ptr] != 0)
                {
                    tape[ptr] -= 1;
                    ptr += 2;
                    tape[ptr] += 1;
                    ptr -= 3;
                }
                ptr -= 2;
                tape[ptr] -= 1;
                ptr -= 1;
            }
            ptr -= 4;
            tape[ptr] += 1;
            ptr += 1;
            while (tape[ptr] != 0)
            {
                ptr -= 1;
                tape[ptr] -= 1;
            }
            ptr -= 1;
            while (tape[ptr] != 0)
            {
                ptr += 2;
                while (tape[ptr] != 0)
                {
                    ptr -= 2;
                    tape[ptr] -= 1;
                    ptr += 1;
                }
                ptr -= 2;
                while (tape[ptr] != 0)
                {
                    ptr -= 1;
                }
            }
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr += 2;
        tape[ptr] += 8;
        while (tape[ptr] != 0)
        {
            tape[ptr] -= 1;
            ptr += 1;
            tape[ptr] += 6;
            ptr -= 1;
        }
        ptr += 1;
        while (tape[ptr] != 0)
        {
            tape[ptr] -= 1;
            ptr -= 4;
            tape[ptr] += 1;
            ptr += 4;
        }
        ptr += 5;
        tape[ptr] += 1;
        ptr += 1;
        ptr -= 1;
        ptr += 1;
        tape[ptr] -= 1;
        tape[ptr] += 1;
        while (tape[ptr] != 0)
        {
            ptr -= 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0)
        {
            ptr += 2;
            while (tape[ptr] != 0)
            {
                ptr -= 2;
                tape[ptr] -= 1;
                ptr += 1;
            }
            ptr -= 2;
            while (tape[ptr] != 0)
            {
                ptr -= 1;
            }
        }
        ptr += 1;
        tape[ptr] -= 1;
        while (tape[ptr] != 0)
        {
            tape[ptr] += 2;
            ptr += 1;
            while (tape[ptr] != 0)
            {
                ptr -= 1;
                tape[ptr] -= 1;
            }
            ptr -= 1;
            while (tape[ptr] != 0)
            {
                tape[ptr] -= 1;
                ptr += 2;
                tape[ptr] -= 1;
                ptr -= 3;
            }
            ptr += 2;
            tape[ptr] -= 1;
            ptr -= 8;
            tape[ptr] += 1;
            ptr += 1;
            tape[ptr] += 1;
            while (tape[ptr] != 0)
            {
                ptr -= 1;
                tape[ptr] -= 1;
            }
            ptr -= 1;
            while (tape[ptr] != 0)
            {
                tape[ptr] -= 1;
                ptr += 2;
                tape[ptr] += 1;
                ptr -= 3;
            }
            ptr += 8;
            tape[ptr] += 1;
            ptr += 1;
            while (tape[ptr] != 0)
            {
                ptr -= 1;
                tape[ptr] -= 1;
            }
            ptr -= 1;
            while (tape[ptr] != 0)
            {
                ptr += 2;
                while (tape[ptr] != 0)
                {
                    ptr -= 2;
                    tape[ptr] -= 1;
                    ptr += 1;
                }
                ptr -= 2;
                while (tape[ptr] != 0)
                {
                    ptr -= 1;
                }
            }
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 2;
        while (tape[ptr] != 0)
        {
            tape[ptr] -= 1;
        }
        ptr -= 5;
        tape[ptr] += 1;
        ptr += 1;
        while (tape[ptr] != 0)
        {
            ptr -= 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0)
        {
            ptr += 2;
            while (tape[ptr] != 0)
            {
                ptr -= 2;
                tape[ptr] -= 1;
                ptr += 1;
            }
            ptr -= 2;
            while (tape[ptr] != 0)
            {
                ptr -= 1;
            }
        }
        ptr += 1;
        tape[ptr] -= 1;
    }
    ptr -= 2;
    while (tape[ptr] != 0)
    {
        printf("%c",tape[ptr]);
        ptr -= 1;
    }

}

